name: Deploy to server

on:
  workflow_dispatch:
  push:

jobs:
  build-for-one:
    strategy:
      matrix:
        directory: [ core, forecast, rule, schedule, staff, store ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: '18'
      - name: Dependicies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile Module ${{ matrix.directory }}
        run: mvn clean install -pl ${{ matrix.directory }} -am -DskipTests
      - name: Upload Module ${{ matrix.directory }} to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ matrix.directory }}/target/${{ matrix.directory }}-0.0.1-SNAPSHOT.jar
          remote: schedulesystem/${{ matrix.directory }}-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run Module ${{ matrix.directory }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd schedulesystem
            sh run.sh ${{ matrix.directory }}-0.0.1-SNAPSHOT

  build-core:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'core/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Core
        run: echo "Build Core"
  build-forecast:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'forecast/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Forecast
        run: echo "Build Forecast"
  build-rule:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'rule/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Rule
        run: echo "Build Rule"
  build-schedule:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'schedule/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Schedule
        run: echo "Build Schedule"
  build-staff:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'staff/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Staff
        run: echo "Build Staff"
  build-store:
    needs: [ build-for-one ]
    if: startsWith(github.event_path, 'store/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Store
        run: echo "Build Store"