name: Deploy to server

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    strategy:
      matrix:
        directory: [ core, forecast, rule, schedule, staff, store ]
    runs-on: ubuntu-latest
    if: startsWith(github.event_path, '${{ matrix.directory }}/')
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: '18'
      - name: Dependicies Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Compile Module ${{ matrix.directory }}
        run: mvn clean install -pl ${{ matrix.directory }} -am -DskipTests
      - name: Upload Module ${{ matrix.directory }} to Server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ matrix.directory }}/target/${{ matrix.directory }}-0.0.1-SNAPSHOT.jar
          remote: schedulesystem/${{ matrix.directory }}-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run Module ${{ matrix.directory }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd schedulesystem
            sh run.sh ${{ matrix.directory }}-0.0.1-SNAPSHOT